# Generated by Django 5.0 on 2024-01-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fruit_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Fruit name')),
                ('price', models.FloatField()),
                ('benefit', models.CharField(max_length=100, verbose_name='fruit benefit')),
                ('cat', models.IntegerField(choices=[(1, 'Fleshy Fruit'), (2, 'Dry Fruit')], verbose_name='fruit type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('fimage', models.ImageField(upload_to='image/fruits')),
            ],
        ),
        migrations.CreateModel(
            name='juice_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Juice name')),
                ('price', models.FloatField()),
                ('benefit', models.CharField(max_length=100, verbose_name='juice benefit')),
                ('juicecat', models.IntegerField(choices=[(1, 'Fresh Fruit Juice'), (2, 'FC Juice(From Concentrate)'), (3, 'NFC Juice(Non From Concentrate)'), (4, 'Cold Press Juice'), (5, 'Fruity Drinks')], verbose_name='juice type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('jimage', models.ImageField(upload_to='image/fruits')),
            ],
        ),
        migrations.CreateModel(
            name='FruitAddCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='fruitapp.fruit_product')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FruitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='fruitapp.fruit_product')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JuiceAddCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='fruitapp.juice_product')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JuiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='fruitapp.juice_product')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
