# Generated by Django 5.0 on 2024-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit_product',
            name='benefit',
            field=models.CharField(max_length=800, verbose_name='fruit benefit'),
        ),
        migrations.AlterField(
            model_name='juice_product',
            name='benefit',
            field=models.CharField(max_length=800, verbose_name='juice benefit'),
        ),
    ]
